//
//  SampleData.swift
//  EpitApp
//
//  Created by Quenting on 16/06/2025.
//

var courseCacheSampleData = """
[
    {
        "idReservation": 1,
        "idCourse": 101,
        "name": "Introduction to Computer Science",
        "idType": 1,
        "typeName": "Lecture",
        "startDate": "2024-01-01T08:00:00Z",
        "endDate": "2024-01-01T10:00:00Z",
        "isOnline": false,
        "rooms": [{"id": 1, "capacity": 50, "name": "Room 101", "idRoomType": 1, "idLocation": 1, "isVisible": true}],
        "groups": [{"id": 1, "name": "Group A", "count": 30, "idSchool": 1, "color": "#FF0000", "isVisible": true}],
        "teachers": [{"id": 1, "name": "Doe", "firstname": "John"}],
        "idSchool": 1,
        "schoolName": "School of Engineering"
    },
    {
        "idReservation": 2,
        "idCourse": 102,
        "name": "Advanced Mathematics",
        "idType": 2,
        "typeName": "Seminar",
        "startDate": "2024-01-01T10:30:00Z",
        "endDate": "2024-01-01T12:30:00Z",
        "isOnline": true,
        "rooms": [{"id": 2, "capacity": 40, "name": "Room 202", "idRoomType": 2, "idLocation": 2, "isVisible": true}],
        "groups": [{"id": 2, "name": "Group B", "count": 25, "idSchool": 2, "color": "#00FF00", "isVisible": true}],
        "teachers": [{"id": 2, "name": "Smith", "firstname": "Jane"}],
        "idSchool": 2,
        "schoolName": "School of Science"
    },
    {
        "idReservation": 3,
        "idCourse": 103,
        "name": "Physics Fundamentals",
        "idType": 1,
        "typeName": "Lecture",
        "startDate": "2024-01-01T13:30:00Z",
        "endDate": "2024-01-01T15:30:00Z",
        "isOnline": false,
        "rooms": [{"id": 3, "capacity": 60, "name": "Room 303", "idRoomType": 3, "idLocation": 3, "isVisible": true}],
        "groups": [{"id": 3, "name": "Group C", "count": 35, "idSchool": 3, "color": "#0000FF", "isVisible": true}],
        "teachers": [{"id": 3, "name": "Johnson", "firstname": "Robert"}],
        "idSchool": 3,
        "schoolName": "School of Physical Sciences"
    },
    {
        "idReservation": 4,
        "idCourse": 104,
        "name": "Chemistry Basics",
        "idType": 2,
        "typeName": "Seminar",
        "startDate": "2024-01-02T08:00:00Z",
        "endDate": "2024-01-02T10:00:00Z",
        "isOnline": true,
        "rooms": [{"id": 4, "capacity": 45, "name": "Room 404", "idRoomType": 4, "idLocation": 4, "isVisible": true}],
        "groups": [{"id": 4, "name": "Group D", "count": 20, "idSchool": 4, "color": "#FFFF00", "isVisible": true}],
        "teachers": [{"id": 4, "name": "Williams", "firstname": "Emily"}],
        "idSchool": 4,
        "schoolName": "School of Chemical Sciences"
    },
    {
        "idReservation": 5,
        "idCourse": 105,
        "name": "Introduction to Biology",
        "idType": 1,
        "typeName": "Lecture",
        "startDate": "2024-01-02T10:30:00Z",
        "endDate": "2024-01-02T12:30:00Z",
        "isOnline": false,
        "rooms": [{"id": 5, "capacity": 55, "name": "Room 505", "idRoomType": 5, "idLocation": 5, "isVisible": true}],
        "groups": [{"id": 5, "name": "Group E", "count": 30, "idSchool": 5, "color": "#FF00FF", "isVisible": true}],
        "teachers": [{"id": 5, "name": "Brown", "firstname": "Michael"}],
        "idSchool": 5,
        "schoolName": "School of Life Sciences"
    },
    {
        "idReservation": 6,
        "idCourse": 106,
        "name": "Data Structures",
        "idType": 1,
        "typeName": "Lecture",
        "startDate": "2024-01-03T08:00:00Z",
        "endDate": "2024-01-03T10:00:00Z",
        "isOnline": false,
        "rooms": [{"id": 6, "capacity": 50, "name": "Room 106", "idRoomType": 1, "idLocation": 1, "isVisible": true}],
        "groups": [{"id": 6, "name": "Group F", "count": 30, "idSchool": 1, "color": "#00FFFF", "isVisible": true}],
        "teachers": [{"id": 6, "name": "Taylor", "firstname": "Sophia"}],
        "idSchool": 1,
        "schoolName": "School of Engineering"
    },
    {
        "idReservation": 7,
        "idCourse": 107,
        "name": "Algorithms",
        "idType": 2,
        "typeName": "Seminar",
        "startDate": "2024-01-03T10:30:00Z",
        "endDate": "2024-01-03T12:30:00Z",
        "isOnline": true,
        "rooms": [{"id": 7, "capacity": 40, "name": "Room 207", "idRoomType": 2, "idLocation": 2, "isVisible": true}],
        "groups": [{"id": 7, "name": "Group G", "count": 25, "idSchool": 2, "color": "#FF9900", "isVisible": true}],
        "teachers": [{"id": 7, "name": "Anderson", "firstname": "Liam"}],
        "idSchool": 2,
        "schoolName": "School of Science"
    },
    {
        "idReservation": 8,
        "idCourse": 108,
        "name": "Organic Chemistry",
        "idType": 1,
        "typeName": "Lecture",
        "startDate": "2024-01-03T13:30:00Z",
        "endDate": "2024-01-03T15:30:00Z",
        "isOnline": false,
        "rooms": [{"id": 8, "capacity": 60, "name": "Room 308", "idRoomType": 3, "idLocation": 3, "isVisible": true}],
        "groups": [{"id": 8, "name": "Group H", "count": 35, "idSchool": 3, "color": "#9900FF", "isVisible": true}],
        "teachers": [{"id": 8, "name": "Martinez", "firstname": "Olivia"}],
        "idSchool": 3,
        "schoolName": "School of Physical Sciences"
    },
    {
        "idReservation": 9,
        "idCourse": 109,
        "name": "Genetics",
        "idType": 2,
        "typeName": "Seminar",
        "startDate": "2024-01-04T08:00:00Z",
        "endDate": "2024-01-04T10:00:00Z",
        "isOnline": true,
        "rooms": [{"id": 9, "capacity": 45, "name": "Room 409", "idRoomType": 4, "idLocation": 4, "isVisible": true}],
        "groups": [{"id": 9, "name": "Group I", "count": 20, "idSchool": 4, "color": "#00FF99", "isVisible": true}],
        "teachers": [{"id": 9, "name": "Garcia", "firstname": "Noah"}],
        "idSchool": 4,
        "schoolName": "School of Chemical Sciences"
    },
    {
        "idReservation": 10,
        "idCourse": 110,
        "name": "Ecology",
        "idType": 1,
        "typeName": "Lecture",
        "startDate": "2024-01-04T10:30:00Z",
        "endDate": "2024-01-04T12:30:00Z",
        "isOnline": false,
        "rooms": [{"id": 10, "capacity": 55, "name": "Room 510", "idRoomType": 5, "idLocation": 5, "isVisible": true}],
        "groups": [{"id": 10, "name": "Group J", "count": 30, "idSchool": 5, "color": "#FF0099", "isVisible": true}],
        "teachers": [{"id": 10, "name": "Robinson", "firstname": "Ava"}],
        "idSchool": 5,
        "schoolName": "School of Life Sciences"
    },
    {
        "idReservation": 11,
        "idCourse": 111,
        "name": "Software Engineering",
        "idType": 1,
        "typeName": "Lecture",
        "startDate": "2024-01-05T08:00:00Z",
        "endDate": "2024-01-05T10:00:00Z",
        "isOnline": false,
        "rooms": [{"id": 11, "capacity": 50, "name": "Room 111", "idRoomType": 1, "idLocation": 1, "isVisible": true}],
        "groups": [{"id": 11, "name": "Group K", "count": 30, "idSchool": 1, "color": "#99FF00", "isVisible": true}],
        "teachers": [{"id": 11, "name": "Clark", "firstname": "James"}],
        "idSchool": 1,
        "schoolName": "School of Engineering"
    },
    {
        "idReservation": 12,
        "idCourse": 112,
        "name": "Database Systems",
        "idType": 2,
        "typeName": "Seminar",
        "startDate": "2024-01-05T10:30:00Z",
        "endDate": "2024-01-05T12:30:00Z",
        "isOnline": true,
        "rooms": [{"id": 12, "capacity": 40, "name": "Room 212", "idRoomType": 2, "idLocation": 2, "isVisible": true}],
        "groups": [{"id": 12, "name": "Group L", "count": 25, "idSchool": 2, "color": "#0099FF", "isVisible": true}],
        "teachers": [{"id": 12, "name": "Rodriguez", "firstname": "Emma"}],
        "idSchool": 2,
        "schoolName": "School of Science"
    },
    {
        "idReservation": 13,
        "idCourse": 113,
        "name": "Quantum Mechanics",
        "idType": 1,
        "typeName": "Lecture",
        "startDate": "2024-01-05T13:30:00Z",
        "endDate": "2024-01-05T15:30:00Z",
        "isOnline": false,
        "rooms": [{"id": 13, "capacity": 60, "name": "Room 313", "idRoomType": 3, "idLocation": 3, "isVisible": true}],
        "groups": [{"id": 13, "name": "Group M", "count": 35, "idSchool": 3, "color": "#FF6600", "isVisible": true}],
        "teachers": [{"id": 13, "name": "Lewis", "firstname": "William"}],
        "idSchool": 3,
        "schoolName": "School of Physical Sciences"
    },
    {
        "idReservation": 14,
        "idCourse": 114,
        "name": "Biochemistry",
        "idType": 2,
        "typeName": "Seminar",
        "startDate": "2024-01-06T08:00:00Z",
        "endDate": "2024-01-06T10:00:00Z",
        "isOnline": true,
        "rooms": [{"id": 14, "capacity": 45, "name": "Room 414", "idRoomType": 4, "idLocation": 4, "isVisible": true}],
        "groups": [{"id": 14, "name": "Group N", "count": 20, "idSchool": 4, "color": "#6600FF", "isVisible": true}],
        "teachers": [{"id": 14, "name": "Walker", "firstname": "Mia"}],
        "idSchool": 4,
        "schoolName": "School of Chemical Sciences"
    },
    {
        "idReservation": 15,
        "idCourse": 115,
        "name": "Microbiology",
        "idType": 1,
        "typeName": "Lecture",
        "startDate": "2024-01-06T10:30:00Z",
        "endDate": "2024-01-06T12:30:00Z",
        "isOnline": false,
        "rooms": [{"id": 15, "capacity": 55, "name": "Room 515", "idRoomType": 5, "idLocation": 5, "isVisible": true}],
        "groups": [{"id": 15, "name": "Group O", "count": 30, "idSchool": 5, "color": "#00FF66", "isVisible": true}],
        "teachers": [{"id": 15, "name": "Hall", "firstname": "Benjamin"}],
        "idSchool": 5,
        "schoolName": "School of Life Sciences"
    },
    {
        "idReservation": 16,
        "idCourse": 116,
        "name": "Artificial Intelligence",
        "idType": 1,
        "typeName": "Lecture",
        "startDate": "2024-01-07T08:00:00Z",
        "endDate": "2024-01-07T10:00:00Z",
        "isOnline": false,
        "rooms": [{"id": 16, "capacity": 50, "name": "Room 116", "idRoomType": 1, "idLocation": 1, "isVisible": true}],
        "groups": [{"id": 16, "name": "Group P", "count": 30, "idSchool": 1, "color": "#FF0066", "isVisible": true}],
        "teachers": [{"id": 16, "name": "Young", "firstname": "Charlotte"}],
        "idSchool": 1,
        "schoolName": "School of Engineering"
    },
    {
        "idReservation": 17,
        "idCourse": 117,
        "name": "Machine Learning",
        "idType": 2,
        "typeName": "Seminar",
        "startDate": "2024-01-07T10:30:00Z",
        "endDate": "2024-01-07T12:30:00Z",
        "isOnline": true,
        "rooms": [{"id": 17, "capacity": 40, "name": "Room 217", "idRoomType": 2, "idLocation": 2, "isVisible": true}],
        "groups": [{"id": 17, "name": "Group Q", "count": 25, "idSchool": 2, "color": "#66FF00", "isVisible": true}],
        "teachers": [{"id": 17, "name": "Allen", "firstname": "Henry"}],
        "idSchool": 2,
        "schoolName": "School of Science"
    },
    {
        "idReservation": 18,
        "idCourse": 118,
        "name": "Thermodynamics",
        "idType": 1,
        "typeName": "Lecture",
        "startDate": "2024-01-07T13:30:00Z",
        "endDate": "2024-01-07T15:30:00Z",
        "isOnline": false,
        "rooms": [{"id": 18, "capacity": 60, "name": "Room 318", "idRoomType": 3, "idLocation": 3, "isVisible": true}],
        "groups": [{"id": 18, "name": "Group R", "count": 35, "idSchool": 3, "color": "#0066FF", "isVisible": true}],
        "teachers": [{"id": 18, "name": "King", "firstname": "Amelia"}],
        "idSchool": 3,
        "schoolName": "School of Physical Sciences"
    },
    {
        "idReservation": 19,
        "idCourse": 119,
        "name": "Environmental Science",
        "idType": 2,
        "typeName": "Seminar",
        "startDate": "2024-01-08T08:00:00Z",
        "endDate": "2024-01-08T10:00:00Z",
        "isOnline": true,
        "rooms": [{"id": 19, "capacity": 45, "name": "Room 419", "idRoomType": 4, "idLocation": 4, "isVisible": true}],
        "groups": [{"id": 19, "name": "Group S", "count": 20, "idSchool": 4, "color": "#FF6600", "isVisible": true}],
        "teachers": [{"id": 19, "name": "Wright", "firstname": "Lucas"}],
        "idSchool": 4,
        "schoolName": "School of Chemical Sciences"
    },
    {
        "idReservation": 20,
        "idCourse": 120,
        "name": "Neuroscience",
        "idType": 1,
        "typeName": "Lecture",
        "startDate": "2024-01-08T10:30:00Z",
        "endDate": "2024-01-08T12:30:00Z",
        "isOnline": false,
        "rooms": [{"id": 20, "capacity": 55, "name": "Room 520", "idRoomType": 5, "idLocation": 5, "isVisible": true}],
        "groups": [{"id": 20, "name": "Group T", "count": 30, "idSchool": 5, "color": "#6600FF", "isVisible": true}],
        "teachers": [{"id": 20, "name": "Scott", "firstname": "Evelyn"}],
        "idSchool": 5,
        "schoolName": "School of Life Sciences"
    }
]
"""
